### ISSUE TITLE
Finish about page

### ISSUE THREAD

**Issue by bwencke** [IndyTechFellowship/United-Way-Web#140]
Content to be added on GDrive: https://drive.google.com/open?id=1CSH67EMMx5-4TpWWDuqTNB79uMZ6Byv7QlMEpauJQMY

**Comment by BastianHub** [comment]
Content to be added on GDrive: https://drive.google.com/open?id=1CSH67EMMx5-4TpWWDuqTNB79uMZ6Byv7QlMEpauJQMY

**Comment by bwencke** [comment]
1 hour
